language: python

python:
- 2.7

before_install:
    pip install codecov, codeclimate-test-reporter

install: pip install sqlalchemy

script: nosetests

after_sucess:
    codecov
    codeclimate-test-reporter