language: python

python:
- 2.7
- 3.5


install: pip install sqlalchemy

script: nosetests --with-coverage

before_install:
    pip install codecov
after_sucess:
    codecov --token=6a49f528-5c47-4a4f-b302-43d6f5a8b6ad