language: python

python:
- 2.7
- 3.5

before_install:
    -pip install codecov
    -pip install codeclimate-test-reporter

install: pip install sqlalchemy

script: nosetests

after_sucess:
    -codecov
    -codeclimate-test-reporter